# Generated by Django 5.2 on 2025-04-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title',), 'verbose_name_plural': 'movies'},
        ),
    ]
